---
title: "A Economic Realities of Climate Change for the Montana Ski Industry"
output: html_notebook
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(sf)
library(magrittr)
```

```{r ski areas}
ski_area_catalog <-
  "https://skimap.org/SkiAreas/index.xml" %>%
  httr::GET(
    httr::write_disk("data-raw/ski_area_catalog.xml",
                     overwrite = TRUE)
  )

ski_areas <-
  ski_area_catalog %>%
  httr::content() %>%
  xml2::as_list() %$%
  skiAreas %>%
  purrr::map_chr(attr,"id") %>%
  as.integer() %T>%
  purrr::walk(
    function(x){
      if(!file.exists(paste0("data-raw/ski_areas/",x,".json"))){
        paste0("https://skimap.org/SkiAreas/view/",x,".json") %>%
          httr::GET(
            httr::write_disk(paste0("data-raw/ski_areas/",x,".json"),
                             overwrite = FALSE)
          )
      }
    }
  ) %>%
  # magrittr::extract(1:10) %>%
  purrr::map_dfr(function(x){
    area_data <-
      paste0("data-raw/ski_areas/",x,".json") %>%
      jsonlite::fromJSON() %>%
      purrr::compact()

    area_data$ski_maps <- list(as.integer(area_data$ski_maps$id))
    area_data$tags <- list(area_data$tags$name)
    area_data$user <- list(as.integer(area_data$user$id))
    area_data$regions <- list(as.character(area_data$regions$name))

    area_data %>%
      purrr::map(function(x){

        if(length(x) > 1 | any(dim(x) > 1))
          list(x)
        # else if(any(dim(x) > 1))
        #   list(tibble::as_tibble(x))
        else
          x
      }) %>%
      tibble::as_tibble() %>%
      dplyr::mutate_if(is.character,function(x){
        dplyr::na_if(x,"")
      }) %>%
      dplyr::mutate(id = as.integer(id))
  })  %T>%
  readr::write_rds("data-derived/ski_areas_raw.rds") %>%
  dplyr::filter(!is.na(latitude),
                !is.na(longitude),
                operating_status %in% c("Operating", "Unknown")) %>%
  dplyr::rowwise() %>%
  dplyr::filter(!("Fantasy Land" %in% regions)) %>%
  dplyr::ungroup() %>%
  dplyr::select(-regions,-operating_status) %>%
  sf::st_as_sf(coords = c("longitude","latitude"),
               crs = 4326) %T>%
  sf::write_sf("data-derived/ski_areas.geojson",
               delete_dsn = TRUE)
```

```{r read ski areas}
ski_areas <- sf::read_sf("data-derived/ski_areas.geojson")

```

```{r}
west_states <-
  rnaturalearth::ne_states(country = 'united states of america') %>%
  sf::st_as_sf() %>%
  dplyr::filter(region_sub %in% c("Pacific",
                                  "Mountain"),
                !(name %in% c("Alaska",
                            "Hawaii"))) %>%
  dplyr::select(name) %>%
  dplyr::rename(state = name)

ski_areas_western_usa <-
  ski_areas %>%
  sf::st_intersection(west_states) %>%
  dplyr::filter(lift_count > 1 | is.na(lift_count)) %>%
  dplyr::mutate(geom = sf::st_as_text(geometry)) %T>%
  sf::write_sf("data-derived/ski_areas_western_usa.csv",
               delete_dsn = TRUE,
               layer_options = "GEOMETRY=AS_WKT")

ski_areas_western_usa <- sf::read_sf("data-derived/ski_areas_western_usa.csv",
                                     crs = 4326)
```

```{r get swe}

stars::st_as_stars("https://cida.usgs.gov/thredds/nc/BCSD_mon_VIC.nc")
raster::brick("https://cida.usgs.gov/thredds/dodsC/BCSD_mon_VIC/bcc-csm1-1_rcp26_r1i1p1_swe.nc")


```

